---
name: 'Lint, Unit & Integration Tests'

'on':
  pull_request:

jobs:
  lint-unit:
    uses: test-kitchen/.github/.github/workflows/lint-unit.yml@main

  integration:
    runs-on: ubuntu-latest
    needs: lint-unit
    name: Kitchen Verify
    steps:
      - name: Install Vagrant VirtualBox
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | gpg --dearmor | sudo tee /usr/share/keyrings/oracle-virtualbox-2016.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          echo "deb [signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
          sudo apt-get update
          sudo apt-get install -y software-properties-common vagrant virtualbox-7.0
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        strategy:
          matrix:
            ruby: ["3.3", "3.4"]
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Create & Validate containers
        run: |
          bundle exec kitchen verify
        env:
          CHEF_LICENSE: "accept-no-persist"
